"""Fix auto-increment for id column

Revision ID: 81fe74fea1a5
Revises: 126a210ea45e
Create Date: 2024-12-20 20:01:41.258164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81fe74fea1a5'
down_revision: Union[str, None] = '126a210ea45e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=False)
    # ### end Alembic commands ###
    op.execute("CREATE SEQUENCE groups_id_seq")
    op.execute("ALTER TABLE groups ALTER COLUMN id SET DEFAULT nextval('groups_id_seq')")
    op.execute("SELECT setval('groups_id_seq', (SELECT MAX(id) FROM groups))")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    # ### end Alembic commands ###
    op.execute("ALTER TABLE groups ALTER COLUMN id DROP DEFAULT")
    op.execute("DROP SEQUENCE groups_id_seq")

